name: Test Workflow

on:
  push:
    branches:
      - main
      - LeboDev
      - LeboDev2
      - SkuvaDev
      - LemoDev
      - BhavDev
  pull_request:
    branches:
      - main
      - LeboDev
      - LeboDev2
      - SkuvaDev
      - LemoDev
      - BhavDev

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies using npm ci
      - name: Install dependencies
        run: npm ci
        working-directory: ./Code/Managr

      # Run coverage
      - name: Run coverage
        run: npm run coverage
        working-directory: ./Code/Managr

      # Run tests
      - name: Run tests
        run: npm run test
        working-directory: ./Code/Managr

      - name: Upload coverage reports to Codecov
        if: always()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # Build the project
      - name: Build project
        run: npm run build
        working-directory: ./Code/Managr
