name: Test Workflow

on:
  push:
    branches:
      - main
      - LeboDev2
      
  pull_request:
    branches:
      - main
      - LeboDev2

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Change to /Code/Managr directory
      - name: Change to /Code/Managr directory
        run: cd Code/Managr

      # Install dependencies using npm ci
      - name: Install dependencies
        run: npm ci

      # Run coverage
      - name: Run coverage
        run: npm run coverage

      # Run tests
      - name: Run tests
        run: npm run test

      # Build the project
      - name: Build project
        run: npm run build
